const mongoose = require('mongoose')
 
const accountSchema = new mongoose.Schema({
    userId:{
        type:mongoose.Schema.ObjectId,ref:'User'
    },
    FullName:{
        type:String
    },
    DOB:{
        type:String
    },
    Gender:{
        type:String
    },
    MobileNumber:{
        type:String
    },
    AdharNumber:{
        type:String
    },
    PANNumber:{
        type:String
    },
    City_or_Village:{
        type:String
    },
    District:{
        type:String
    },
    State:{
        type:String
    },
    PINCode:{
        type:String
    },
    Country:{
        type:String
    },
    AccountType:{
        type:String
    },
    InitialDiposit:{
        type:Number
    },
    NomineeName:{
        type:String
    },
    NomineeRelation:{
        type:String
    },
    Nationality:{
        type:String
    },
    AccountApprove:{
        type:Boolean
    }
},
 {timestamps:true}
)

module.exports = mongoose.model("Account",accountSchema)